### ISSUE TITLE
Create tests to check the code exposed in documentation

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#145]
In [Threshold Access Control (TAC) documentation](https://docs.threshold.network/app-development/threshold-access-control-tac) we have a tutorial with nucypher-ts code snippets.

Logically, every change in the nucypher-ts API should be reflected in the documentation. But this process can be easily forgotten.

Some automated tests that help in detecting changes in the API that would affect the documentation could be convenient.

In words of Piotr:

        Perhaps we should have a separate test suite in `nucypher-ts`, `test/docs`, where we keep code examples to be used in documentation. Then, we could copy&paste them with confidence instead of doing a QA on them every time we update the API.

_Originally posted by @piotr-roslaniec in https://github.com/nucypher/nucypher-ts/issues/142#issuecomment-1346391859_

**Comment by piotr-roslaniec** [comment]
I think having a framework that runs code examples in docs is interesting. It's worth noting that since we rely on Gitbook we'd either have to integrate it with Gitbook markdown files or keep a copy of docs in our repo and sync it to Gitbook somehow. 

I was unable o find "code runners" for Gitbook, but keeping our docs in the repo and generating Gitbook from them [is definitely on the table](https://blog.gitbook.com/learn/tips-and-tricks/automatically-generating-content-on-gitbook-with-github-actions).

**Comment by manumonti** [comment]
> I think having a framework that runs code examples in docs is interesting. It's worth noting that since we rely on Gitbook we'd either have to integrate it with Gitbook markdown files or keep a copy of docs in our repo and sync it to Gitbook somehow.
> 
> I was unable o find "code runners" for Gitbook, but keeping our docs in the repo and generating Gitbook from them [is definitely on the table](https://blog.gitbook.com/learn/tips-and-tricks/automatically-generating-content-on-gitbook-with-github-actions).

Thank you for the research, and the link is a great finding, we should consider it.

**Comment by piotr-roslaniec** [comment]
Closed by #147

**Comment by manumonti** [comment]
Since we are changing the Gitbook documentation, this is outdated.
